name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  deploy-lab:
    runs-on: ubuntu-latest
    env: 
      USER: ${{ secrets.SSH_USERNAME }}
      HOST: ${{ secrets.SSH_HOST }}
      REPO_NAME: ${{ vars.REPO_NAME }}
    steps:
    - name: clone to lab
      uses: and-fm/cloudflared-ssh-action@v3
      with:
        host: ${{ env.HOST }}
        username: ${{ env.USER }}
        private_key_value: ${{ secrets.SSH_PRIVATE_KEY_VALUE }}
        private_key_filename: ${{ secrets.SSH_PRIVATE_KEY_FILENAME }}
        port: 22
        commands: |
          cd /home/${{ env.USER }}/lab-rke/${{ env.REPO_NAME}} && echo 'Destory the old infrastructure'
          tofu destroy -auto-approve